USE AddressBook;
DROP TABLE UserTable;
CREATE TABLE UserTable(
   UName                  VARCHAR(20) NOT NULL
  ,UserId                 VARCHAR(30) NOT NULL PRIMARY KEY
  ,Passwd                 VARCHAR(20) NOT NULL
  ,Gender                 VARCHAR(6) NOT NULL
  ,Phone                  VARCHAR(15) NOT NULL
  ,Address                VARCHAR(25) NOT NULL
  ,City                   VARCHAR(25) NOT NULL
  ,Country                VARCHAR(20) NOT NULL
);
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Marilyn Stewart','mStewart@addressbook.com','cxPuD7','Female','9430746323','798 Eagle Road','Austertana','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Janet Martinez','jMartinez@addressbook.com','kNmJ85','Female','9096651559','628 Eagle Road','Bamburgh','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Billy Collins','bCollins@addressbook.com','MwBxvT','Male','9886617186','290 Heather Lane','Basalt','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jesse Simmons','jSimmons@addressbook.com','r4WEKR','Male','8882558005','663 Washington Avenue','Basingstoke','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Frank White','fWhite@addressbook.com','ZDWwG4','Male','8504654031','531 East Avenue','Bebington','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Margaret Carter','mCarter@addressbook.com','zU3v7t','Female','9183067738','794 Hillside Drive','Bergunnhaugen','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Bobby Wood','bWood@addressbook.com','b5eSXM','Male','8228373660','321 Route 10','Bloomfield','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Adam Kelly','aKelly@addressbook.com','TdxH3D','Male','9297274623','107 Oak Street','Boulevard','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Doris Bryant','dBryant@addressbook.com','mWNdGU','Female','8075287663','492 Lexington Court','Brougham','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Mildred Cooper','mCooper@addressbook.com','PPebNm','Female','8846456737','825 Garfield Avenue','Buro','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Craig Sanchez','cSanchez@addressbook.com','MmEj6M','Male','8618712286','363 Spring Street','Butte','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('George Richardson','gRichardson@addressbook.com','z52bmF','Male','7995390355','542 Canterbury Court','Castor','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Tammy Mitchell','tMitchell@addressbook.com','jDkspe','Female','9339211522','936 8th Street','Charamba','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Robert Young','rYoung@addressbook.com','jXsAqC','Male','7922355109','88 Locust Street','Chidonitofaraseyi','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Sean Watson','sWatson@addressbook.com','VkdEa6','Male','8346279841','918 Highland Drive','Chingozhoro','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Philip Murphy','pMurphy@addressbook.com','d5RTRL','Male','9624152046','863 Bridge Street','Chizema','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Andrea Baker','aBaker@addressbook.com','PvxTaT','Female','8277579510','16 Monroe Street','Colonial Heights','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Amy Roberts','aRoberts@addressbook.com','QwVwfQ','Female','7778192370','135 Manor Drive','Denhoff','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Irene Foster','iFoster@addressbook.com','AZu7Kj','Female','8641639570','616 Pearl Street','Dorchester','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Gregory Parker','gParker@addressbook.com','sdscxr','Male','9677770254','549 Hawthorne Lane','Dorking','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Helen Hall','hHall@addressbook.com','LLWBkP','Female','9672962553','561 Sunset Drive','Dunmow','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Barbara Diaz','bDiaz@addressbook.com','Rtecfu','Female','9247320089','260 Park Street','East Foothills','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Clarence Peterson','cPeterson@addressbook.com','ZzrSas','Male','8754320092','36 Chestnut Avenue','East Liberty','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Julie Scott','jScott@addressbook.com','psCjKX','Female','8013003037','684 Chestnut Avenue','Eig','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Beverly Jones','bJones@addressbook.com','sPrnvU','Female','9434463457','272 Academy Street','Ellenton','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('David Rodriguez','dRodriguez@addressbook.com','FxJ5VG','Male','9655479644','393 5th Avenue','Flemingsburg','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Arthur Lopez','aLopez@addressbook.com','FR3WQ3','Male','8641517601','257 Highland Drive','Foot of Ten','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Martin Griffin','mGriffin@addressbook.com','aR9wWA','Male','9342135002','804 Ridge Street','Forsnes','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Bruce Wright','bWright@addressbook.com','Bxphxh','Male','7800673567','326 Poplar Street','Frank','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Lawrence Brown','lBrown@addressbook.com','JkfbqH','Male','8860631485','789 Prospect Avenue','Galta','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Albert Butler','aButler@addressbook.com','vey8AK','Male','8643646957','134 Madison Avenue','Green Ridge','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Nicholas Gonzalez','nGonzalez@addressbook.com','gSN4Ns','Male','8504672416','841 Strawberry Lane','Gwelutshena','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Joseph Phillips','jPhillips@addressbook.com','ZG9Kk8','Male','9111276824','680 7th Street','Haltdalen','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Larry Coleman','lColeman@addressbook.com','py6aPG','Male','8289615380','764 Cherry Lane','Hegge','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jane Richardson','jRichardson@addressbook.com','XbgGDR','Female','7771527094','625 River Road','Horsham','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Kelly Perry','kPerry@addressbook.com','mFdYYs','Female','9600533259','745 Front Street','Hvitstein','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Virginia Campbell','vCampbell@addressbook.com','F2r59V','Female','9313084915','964 Holly Drive','Inyathi','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Anna Cook','aCook@addressbook.com','Dpazeh','Female','8165792352','196 Monroe Street','Island City','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Paul Washington','pWashington@addressbook.com','T8TmLk','Male','7766430840','854 Circle Drive','Johannes','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Nicole Rodriguez','nRodriguez@addressbook.com','3sZzXx','Female','8482941279','846 Canterbury Court','Kanjera','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Mary Griffin','maryGriffin@addressbook.com','pWQsg4','Female','8062548707','821 High Street','Kiberg','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Laura Green','lGreen@addressbook.com','LZBz8V','Female','8011629041','764 West Street','Kurraasen','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Louis Hall','lHall@addressbook.com','swgq8K','Male','8056699607','79 Homestead Drive','Kvitnoes','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jessica Price','jPrice@addressbook.com','nQQ5t6','Female','8931198028','665 Cambridge Court','Landercost','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Kenneth Cooper','kCooper@addressbook.com','rP47EL','Male','9089756632','750 Mill Road','Lavvonjargga','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Donald Perez','dPerez@addressbook.com','WZjyTR','Male','8103756861','486 Roosevelt Avenue','Lichfield','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Louise Morris','lMorris@addressbook.com','Vn7eTJ','Female','8540606078','790 Hillside Drive','Likvern','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Debra Clark','dClark@addressbook.com','GmT4uu','Female','9213473190','429 Cemetery Road','Lincroft','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Anne Kelly','anneKelly@addressbook.com','Y7faat','Female','8111447419','22 B Street','Littlefield','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Earl Thomas','eThomas@addressbook.com','QN5skc','Male','9146048447','519 Route 27','LLawhaden','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Maria Evans','mEvans@addressbook.com','3KpqQE','Female','8862136047','795 Madison Street','Lonin','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Gerald Nelson','gNelson@addressbook.com','jQLjYQ','Male','9925291413','543 Country Lane','Lyme','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jeffrey Sanders','jSanders@addressbook.com','cdKh2v','Male','8138422947','658 Clinton Street','Machylleth','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jacqueline Lopez','jLopez@addressbook.com','RwkDLx','Female','9008326819','620 Hillcrest Drive','Malmesbury','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Norma Wood','nWood@addressbook.com','ux2J3u','Female','8577514174','851 George Street','Mapolisa','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Diane Harris','dHarris@addressbook.com','SDhZ7b','Female','8595174501','432 Monroe Drive','Monon','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jack Robinson','jRobinson@addressbook.com','3t2n4R','Male','8359765180','617 Franklin Court','Morecambe','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Roger Garcia','rGarcia@addressbook.com','tNeNmY','Male','9885816493','903 Green Street','Muchiriri-Zenda','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Shawn Davis','sDavis@addressbook.com','Mdvxkt','Male','8979687769','924 4th Street','Muduma','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Ruth Ramirez','rRamirez@addressbook.com','QZuwfy','Female','9747008092','905 7th Avenue','Mungesi','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Wayne Thompson','wThompson@addressbook.com','UqmU2U','Male','8892750034','965 Route 100','Murwiri','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Victor Russell','vRussell@addressbook.com','VWqpH7','Male','9144796617','963 College Avenue','Mushaikwa','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Timothy Alexander','tAlexander@addressbook.com','7Qy7dM','Male','9656271958','957 Elmwood Avenue','Muziomutsha','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Rachel Wright','rWright@addressbook.com','XRnmnH','Female','9587085191','87 Penn Street','Mvudhlana','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Tina Robinson','tRobinson@addressbook.com','aNsXKK','Female','9917543230','961 Jones Street','Navimadzanwa','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Betty King','bKing@addressbook.com','QPD3Um','Female','9059341677','268 Belmont Avenue','Neosho Falls','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Susan Patterson','sPatterson@addressbook.com','SrUN6d','Female','9165195826','930 Augusta Drive','Neruwembo','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Frances Anderson','fAnderson@addressbook.com','eSkKEN','Female','9207629977','527 5th Street North','Newmarket','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Randy Ward','rWard@addressbook.com','SdfxtU','Male','9249378722','88 Central Avenue','Nhengo','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Cynthia Williams','cWilliams@addressbook.com','xuSvvP','Female','9568014102','385 Williams Street','North Pearsall','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jerry Bell','jBell@addressbook.com','kFTkSC','Male','8440184902','659 Mulberry Street','Oxted','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Sarah Long','sLong@addressbook.com','xN8Nea','Female','9834678731','91 Grant Avenue','Pelendaba','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Christina Sanders','cSanders@addressbook.com','UZXtmH','Female','9596304784','333 Eagle Road','Pilot Mound','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Chris Williams','chrisWilliams@addressbook.com','wSnCXX','Male','8562912612','331 Fairview Road','Port Dickinson','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Judith Moore','jMoore@addressbook.com','U7SeCv','Female','7790218047','682 Country Lane','Rausand','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Fred Price','fPrice@addressbook.com','Sr8mVE','Male','9061957092','537 Lafayette Avenue','Ravensworth','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Harry Rivera','hRivera@addressbook.com','4VG384','Male','8947295248','557 Columbia Street','Richmond','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Henry Taylor','hTaylor@addressbook.com','3NqMuw','Male','9210132075','587 Aspen Drive','Romsey','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Ernest Smith','eSmith@addressbook.com','MmPVk4','Male','8531022876','523 Schoolhouse Lane','Saurm','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Scott Barnes','sBarnes@addressbook.com','kZ34xK','Male','8062964622','917 Country Club Road','Seke','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('William Evans','wEvans@addressbook.com','Fh3fkw','Male','8224962016','998 Elmwood Avenu','Seki','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Judy Henderson','jHenderson@addressbook.com','U3VYD8','Female','8508726868','682 Valley Road','Sesaas','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Benjamin Cox','bCox@addressbook.com','k5R6Er','Male','9860153826','262 Railroad Street','Shell Knob','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Thomas Howard','tHoward@addressbook.com','pGVa2G','Male','8252679026','940 Vine Street','Sigaqana','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Michael James','mJames@addressbook.com','NcUH5y','Male','8393342984','824 Court Street','Skaaren','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Karen Hernandez','kHernandez@addressbook.com','ZzuAvD','Female','9444210335','689 York Street','Skjelbostad','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Nancy Jenkins','nJenkins@addressbook.com','trQct6','Female','7742419430','84 South Street','Slaattnes','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Ann Smith','aSmith@addressbook.com','NsjtvV','Female','9804602808','169 Willow Avenue','St. Mary of the Woods','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Alice Murphy','aMurphy@addressbook.com','Fa258E','Female','9091986202','134 Sherman Street','Stanaford','United States');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jason Moore','jasonMoore@addressbook.com','4fL5dH','Male','8587064845','630 Route 32','Startford','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Donna Lee','dLee@addressbook.com','WEKqk7','Female','8753913776','488 Hill Street','Stoesay','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Paula Martin','pMartin@addressbook.com','rQYVLu','Female','8838127093','86 John Street','Tavafumisa','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Martha Thompson','mThompson@addressbook.com','whXABj','Female','9657449705','8 Hillcrest Avenue','Trollfjordbotn','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Jose Walker','jWalker@addressbook.com','sUxsjG','Male','9686502963','676 Route 2','Valdres','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Juan Clark','jClark@addressbook.com','ZayvNy','Male','8329770870','680 Locust Street','Vasstrand','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Lois Taylor','lTaylor@addressbook.com','7Zk6bh','Female','8467647467','789 Shady Lane','Vebbestad','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Kathryn Sanchez','kSanchez@addressbook.com','vVPCkt','Female','9646501965','712 Route 11','Visnes','Norway');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Shirley Howard','sHoward@addressbook.com','ER2asC','Female','8104748927','925 East Street','Vrede','Zimbabwe');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Harold Harris','hHarris@addressbook.com','SFpWYx','Male','8416942849','550 Heritage Drive','Wenlock','England');
INSERT INTO UserTable(UName,UserId,Passwd,Gender,Phone,Address,City,Country) VALUES ('Deborah White','dWhite@addressbook.com','YZKC7f','Female','9741419421','426 Cleveland Avenue','Amaya','United States');
